"""Add annotation_class_id to Annotation model

Revision ID: 89e443869082
Revises: 8c403b6e7c7f
Create Date: 2025-05-03 23:04:56.442375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e443869082'
down_revision = '8c403b6e7c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annotation_class_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'annotation_class', ['annotation_class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('annotation_class_id')

    # ### end Alembic commands ###
