"""Add semi-supervised learning fields

Revision ID: 9853f73a3b7b
Revises: e0bef84a7e9a
Create Date: 2025-05-05 12:31:59.117024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9853f73a3b7b'
down_revision = 'e0bef84a7e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_annotated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_annotated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('auto_annotated')
        batch_op.drop_column('is_annotated')

    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_column('confidence')

    # ### end Alembic commands ###
