"""Add current_epoch to Model

Revision ID: e0bef84a7e9a
Revises: 89e443869082
Create Date: 2025-05-04 14:52:57.941991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0bef84a7e9a'
down_revision = '89e443869082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation_class')
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.drop_column('data')
        batch_op.drop_column('annotation_type')

    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_epoch', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_column('current_epoch')

    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annotation_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('data', sa.TEXT(), nullable=True))

    op.create_table('annotation_class',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
